= Create A Kubernetes Cluster
:toc:
:icons:
:linkattrs:
:imagesdir: ../../resources/images

This section will walk you through how to install a Kubernetes cluster on AWS using EKS.

link:https://aws.amazon.com/eks/[Amazon Elastic Container Service for Kubernetes, window="_blank"] (Amazon EKS) makes it easy to deploy, manage, and scale containerized applications using Kubernetes on AWS.

Amazon EKS runs the Kubernetes management infrastructure for you across multiple AWS availability zones to eliminate a single point of failure. Amazon EKS is certified Kubernetes conformant so you can use existing tooling and plugins from partners and the Kubernetes community. Applications running on any standard Kubernetes environment are fully compatible and can be easily migrated to Amazon EKS.

If you have not set up the link:../101-start-here[Cloud9 Development Environment, window="_blank"] yet, please do so before continuing.

== Permissions

In order to complete the exercises in the workshop, you'll need the proper IAM permissions set.

=== Cloud9 IDE
When performing the exercises through the Cloud9 IDE (recommended), permissions are automatically created for when you link:https://github.com/dewjam/aws-workshop-for-kubernetes/tree/master/01-container-basics/101-start-here[deploy the Cloud9 environment and build the utilities container].

The IAM role assumed by the Cloud9 IDE will have a name similar to **k8s-workshop-LabIdeRole-xxxx**, and contain the following managed policies:

* AmazonEC2FullAccess
* IAMFullAccess
* AmazonS3FullAccess
* AmazonVPCFullAccess
* AWSCloudFormationReadOnlyAccess
* AmazonRoute53FullAccess

The EKS service role will have a name similar to **k8s-workshop2-EksServiceR-AWSServiceRoleForAmazonE-xxx**, and contain the following managed policies:

* AmazonEKSClusterPolicy
* AmazonEKSServicePolicy

== Create a Kubernetes Cluster with EKS

EKS can be used to create a highly available cluster, with multiple master nodes spread across multiple availability zones.

=== Create the master nodes

Create a Kubernetes cluster using the following command. Run it in the "bash" terminal tab at the bottom of the Cloud9 IDE. This will create a cluster with master nodes:

Make sure to change the name of your cluster to something unique!

    $ aws eks create-cluster \
      --name ${EKS_CLUSTER_NAME} \
      --role-arn ${EKS_SERVICE_ROLE} \
      --resources-vpc-config subnetIds=${EKS_SUBNET_IDS},securityGroupIds=${EKS_SECURITY_GROUPS} \
      --kubernetes-version 1.12

The `EKS_SERVICE_ROLE`, `EKS_SUBNET_IDS`, and `EKS_SECURITY_GROUPS` environment variables should have been set during the link:../101-start-here[Cloud9 Environment Setup].

Cluster provisioning usually takes less than 10 minutes. You can query the status of your cluster with the following command. When your cluster status is `ACTIVE`, you can proceed.

    $ watch "aws eks describe-cluster --name ${EKS_CLUSTER_NAME} --query cluster.status --output text"

Note: If your 'create cluster' fails with an error like:
```
aws: error: argument --role-arn: expected one argument
```
Please confirm the following environment variables are set before executing the 'create cluster' command:
```
echo $EKS_SERVICE_ROLE
echo $EKS_SUBNET_IDS
echo $EKS_SECURITY_GROUPS
```
If any of those environment variables are blank, please re-run the "Build Script" section of the link:../101-start-here[Cloud9 Environment Setup].

If you receive an *UnsupportedAvailabilityZoneException* error during EKS cluster creation, your account is using an AZ that is currently resource constrained. This occurs mostly in N.Virginia region (us-east-1).

```
An error occurred (UnsupportedAvailabilityZoneException) when calling the CreateCluster operation: Cannot create cluster 'k8s-workshop' because us-east-1c,
the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1d
```

If you receive this error, you need to remove the constrained AZ (us-east-1c in this example) from *`EKS_SUBNET_IDS`* environment variable. Follow these steps to update your environment variable.

Save the EKS recommended AZ's that is referred in your CLI output in an environment variable.
Note: you only need two AZ's defined to create EKS cluster

    $ export EKS_VALID_AZS=us-east-1a,us-east-1b

Run the command below to determine subnet ID's

    $ aws ec2 describe-subnets --filters "Name=vpc-id,Values=$EKS_VPC_ID" "Name=availabilityZone,Values=$EKS_VALID_AZS" --query 'Subnets[*].[SubnetId]' --output text
    subnet-6e672524
    subnet-18b10e44

Save this output as `*EKS_SUBNET_IDS*` environment variable

    $ export EKS_SUBNET_IDS=subnet-6e672524,subnet-18b10e44

Re-run EKS create-cluster and you should now be able to create cluster. The output should look similar to this

    {
    "cluster": {
        "status": "CREATING",
        "name": "k8s-workshop",
        "certificateAuthority": {},
        "roleArn": "arn:aws:iam::123456789012:role/k8s-workshop-EksServiceRo-AWSServiceRoleForAmazonE-1PCSJFFFAF4BL",
        "resourcesVpcConfig": {
            "subnetIds": [
                "subnet-6e672524",
                "subnet-18b10e44"
            ],
            "vpcId": "vpc-a779b4dd",
            "securityGroupIds": [
                "sg-d093de9a"
            ]
        },
        "version": "1.10",
        "arn": "arn:aws:eks:us-east-1:123456789012:cluster/k8s-workshop",
        "createdAt": 1532734869.147
    }
    }

=== Create the configuration file

In order to access the cluster, you must create a Kubectl configuration file (sometimes referred to as a `kubeconfig` file).
This configuration file can be created automatically via an AWS CLI command.

Once the cluster has moved to the `ACTIVE` state, create the Kubectl Configuration file

    $ aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME}

This will create a configuration file at `$HOME/.kube/config` and update the necessary environment variable for default access.

You can test your kubectl configuration using 'kubectl get service'

    $ kubectl get service
    NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
    kubernetes   ClusterIP   10.100.0.1   <none>        443/TCP   8m

=== Create the worker nodes

Now that your EKS master nodes are created, you can launch and configure your worker nodes.

First, create an SSH key pair for use with your nodes

    $ ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
    $ aws ec2 create-key-pair --key-name ${EKS_NODE_STACK_NAME} --query 'KeyMaterial' --output text > $HOME/.ssh/k8s-workshop.pem

To launch your worker nodes, run the following CloudFormation CLI command:

    $ aws cloudformation create-stack \
      --stack-name ${EKS_NODE_STACK_NAME} \
      --template-url https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2019-02-11/amazon-eks-nodegroup.yaml \
      --capabilities "CAPABILITY_IAM" \
      --parameters "[{\"ParameterKey\": \"KeyName\", \"ParameterValue\": \"${EKS_NODE_STACK_NAME}\"},
                     {\"ParameterKey\": \"NodeImageId\", \"ParameterValue\": \"${EKS_WORKER_AMI}\"},
                     {\"ParameterKey\": \"ClusterName\", \"ParameterValue\": \"${EKS_CLUSTER_NAME}\"},
                     {\"ParameterKey\": \"NodeGroupName\", \"ParameterValue\": \"${EKS_NODE_STACK_NAME}\"},
                     {\"ParameterKey\": \"ClusterControlPlaneSecurityGroup\", \"ParameterValue\": \"${EKS_SECURITY_GROUPS}\"},
                     {\"ParameterKey\": \"VpcId\", \"ParameterValue\": \"${EKS_VPC_ID}\"},
                     {\"ParameterKey\": \"Subnets\", \"ParameterValue\": \"${EKS_SUBNET_IDS}\"}]"

The `AWS_STACK_NAME`, `EKS_WORKER_AMI`, `EKS_VPC_ID`, `EKS_SUBNET_IDS`, and `EKS_SECURITY_GROUPS` environment variables should have been set during the link:../101-start-here[Cloud9 Environment Setup].

=== If your node stack failed, run these commands, then re-run the command above. We need to reference a new cluster security group, then spin up a new cluster that uses it

    $ export EKS_CLUSTER_NAME=<NEW_cluster_name>
    $ export EKS_SECURITY_GROUPS=sg-013a7f92646c0ad6c
    $ aws eks create-cluster \
      --name ${EKS_CLUSTER_NAME} \
      --role-arn ${EKS_SERVICE_ROLE} \
      --resources-vpc-config subnetIds=${EKS_SUBNET_IDS},securityGroupIds=${EKS_SECURITY_GROUPS} \
      --kubernetes-version 1.12

Node provisioning usually takes less than 5 minutes. You can query the status of your cluster with the following command. When your cluster status is `CREATE_COMPLETE`, you can proceed.

    $ watch 'aws cloudformation describe-stacks --stack-name "${EKS_NODE_STACK_NAME}" --query "Stacks[0].[StackStatus,Outputs]"'

**Copy the ARN for the NodeInstanceRole from the output and save it for the next step.**

```
[
    "CREATE_COMPLETE",
    [
        {
            "OutputKey": "NodeInstanceRole",
            "OutputValue": "arn:aws:iam::12345678:role/workshop-eks-nodes-NodeInstanceRole-BHCMWDPXZWBP",
            "Description": "The node instance role"
        },
        {
            "OutputKey": "NodeSecurityGroup",
            "OutputValue": "sg-0284c5c671f9e4ac2",
            "Description": "The security group for the node group"
        }
    ]
]
```

=== Enable worker nodes to join cluster

To enable worker nodes to join your cluster, you must apply a ConfigMap to your cluster including the ARN for the IAM role assigned to
the worker nodes.  Under the `02-eks-cluster-creation/201-your-first-cluster/templates/` folder, open the `aws-auth-cm.yaml` file with
the Cloud9 file editor. Then update the `rolearn` field so it matches the ARN recorded in the previous step.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
```

Next, apply this ConfigMap using the Kubectl command

    $ kubectl apply -f 02-eks-cluster-creation/201-your-first-cluster/templates/aws-auth-cm.yaml

Watch the status of your nodes and wait for them to reach the `Ready` status.

    $ watch kubectl get nodes
    NAME                            STATUS   ROLES    AGE    VERSION
    ip-172-31-36-248.ec2.internal   Ready    <none>   104s   v1.12.7
    ip-172-31-73-146.ec2.internal   Ready    <none>   103s   v1.12.7
    ip-172-31-80-34.ec2.internal    Ready    <none>   104s   v1.12.7

== Kubernetes Cluster Context

You can manage multiple Kubernetes clusters with _kubectl_, the Kubernetes CLI. We will look more deeply at kubectl in the next section. The configuration for each cluster is stored in a configuration file, referred to as the "`kubeconfig file`". By default, kubectl looks for a file named `config` in the directory `~/.kube`. The kubectl CLI uses kubeconfig file to find the information it needs to choose a cluster and communicate with the API server of a cluster.

This allows you to deploy your applications to different environments by just changing the context. For example, here is a typical flow for application development:

. Build your application using a development environment (perhaps even locally on your laptop)
. Change the context to a test cluster created on AWS
. Use the same command to deploy to the test environment
. Once satisfied, change the context again to a production cluster on AWS
. Once again, use the same command to deploy to production environment

Get a summary of available contexts:

  $ kubectl config get-contexts
  CURRENT   NAME      CLUSTER      AUTHINFO   NAMESPACE
  *         aws       kubernetes   aws

The output shows different contexts, one per cluster, that are available to kubectl. `NAME` column shows the context name. `*` indicates the current context.

View the current context:

  $ kubectl config current-context
  aws

If multiple clusters exist, then you can change the context:

  $ kubectl config use-context <config-name>

You are now ready to continue on with the workshop!

:frame: none
:grid: none
:valign: top


The next step is link:../202-kubernetes-concepts[to learn about basic Kubernetes Concepts].
