= Introduction to Containers
:toc:
:icons:
:linkattrs:
:imagesdir: ../../resources/images


== Verify Cloud9 and Docker are Configured

Navigate to the command prompt at the bottom of your Cloud9 IDE. From there, use this command to verify Docker is working.

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.06.1-ce
...
```

== Preparing the Docker Images
At this point, we're going to pretend that we're the developers of both the `web` and `api` microservices, and we will get the latest from our source repo. In this case we will just be using the plain old `curl`, but just pretend you're using `git`:

```
$ curl -O https://s3-us-west-2.amazonaws.com/apn-bootcamps/microservice-ecs-2017/ecs-lab-code-20170524.tar.gz

$ tar -xvf ecs-lab-code-20170524.tar.gz
```

Our first step is to build and test our containers locally. If you've never worked with Docker before, there are a few basic commands that we'll use in this workshop, but you can find a more thorough list in the Docker https://docs.docker.com/get-started/[Getting Started] documentation.

To build your first container, go to the `web` directory. This folder contains our `web` Python Flask microservice:

```
$ cd /home/ec2-user/environment/aws-microservices-ecs-bootcamp-v2/web
```

To build the container:

```
$ docker build -t ecs-lab/web .
```

This should output steps that look something like this:

```
Sending build context to Docker daemon 4.096 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:latest
 ---> 6aa0b6d7eb90
Step 1 : MAINTAINER widha@amazon.com
 ---> Using cache
 ---> 3f2b91d4e7a9
```

If the container builds successfully, the output should end with something like this:

```
Removing intermediate container c16d5287efae
 ---> 3804eb8c2ca3
Successfully built 3804eb8c2ca3
Successfully tagged ecs-lab/web:latest
```

To view the image that was just built:

```
$ docker images
REPOSITORY    TAG      IMAGE ID       CREATED          SIZE
ecs-lab/web   latest   3804eb8c2ca3   28 seconds ago   435MB
```

To run your container:

```
$ docker run -d -p 3000:3000 ecs-lab/web
```

This command runs the image in daemon mode and maps the docker container port 3000 with the host (in this case our workstation) port 3000. We're doing this so that we can run both microservices on a single host without port conflicts.

To check if your container is running:

```
$ docker ps 
```

This should return a list of all the currently running containers. In this example, it should just return a single container, the one that we just started:

```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
a6cc63456133        ecs-lab/web         "python app.py"     28 seconds ago      Up 28 seconds       0.0.0.0:3000->3000/tcp   gracious_jepsen
```

To test the actual container output:

```
$ curl localhost:3000/web
```

This should return

```
<html><head>...</head><body>hi!  i'm served via Python + Flask.  i'm a web endpoint. ...</body></html>
```

Repeat the same steps with the api microservice. Change directory to `/api` and repeat the same steps above.

```
$ cd /home/ec2-user/environment/aws-microservices-ecs-bootcamp-v2/api
$ docker build -t ecs-lab/api .
$ docker images (should see the api image now)
$ docker run -d -p 8000:8000 ecs-lab/api
$ docker ps (should see both containers running)
$ curl localhost:8000/api
```

The API container should return:

```
{ "response" : "hi!  i'm ALSO served via Python + Flask.  i'm an API." }
```

Congradulations, you now have two working microservice containers!

== Creating a container registry with ECR

Once images are built, it’s useful to share them and this is done by pushing the images to a container registry.  Let’s create two repositories in Amazon EC2 Container Registry (https://aws.amazon.com/ecr/[ECR]).

Navigate to the ECS console and Select ECR from AWS Services.

Navigate to *Repositories* and choose *Create repository*.

Name your first repository *eks-lab-web-USERNAME* (replace USERNAME with a unique ID).

Once you've created the `eks-lab-web-USERNAME` repository, repeat the process for the `eks-lab-api-USERNAME` repository. Take note of the push commands for this second repository. Push commands are unique per repository.

Once you've created the repository, select it and then click View Push Commands.

== Configuring the AWS CLI

== Pushing our testing images to ECR

Now that we've tested our images locally, we need to tag and push them to ECR. This will allow us to use them in Task Definitions that can be deployed to an ECS cluster. 

You'll need your push commands that you saw during registry creation. You can find them again by going back to the repository (*ECS Console* > *Repositories* > Select the Repository you want to see the commands for > *View Push Commands*).

To tag and push to the web repository (if you’re using a shared account, use your name in the tag: `NAME-eks-lab:latest`):

```
$ docker tag eks-lab/web:latest <account_id>.dkr.ecr.us-east-1.amazonaws.com/eks-lab-web:latest
$ docker push <account_id>.dkr.ecr.us-east-1.amazonaws.com/eks-lab-web:latest
```

This should return something like this:

```
The push refers to a repository [<account_id>.ecr.us-east-1.amazonaws.com/ecs-lab-web] (len: 1)
ec59b8b825de: Image already exists 
5158f10ac216: Image successfully pushed 
860a4e60cdf8: Image successfully pushed 
6fb890c93921: Image successfully pushed 
aa78cde6a49b: Image successfully pushed 
Digest: sha256:fa0601417fff4c3f3e067daa7e533fbed479c95e40ee96a24b3d63b24938cba8
```

To tag and push to the api repository:

```
$ docker tag eks-lab/api:latest <account_id>.dkr.ecr.us-east-1.amazonaws.com/eks-lab-api:latest
$ docker push <account_id>.dkr.ecr.us-east-1.amazonaws.com/eks-lab-api:latest
```

Note: why `:latest`? This is the actual image tag. In most production environments, you'd tag images for different schemes, for example, you might tag the most up-to-date image with `:latest`, and all other versions of the same container with a commit SHA from a CI job. If you push an image without a specific tag, it will default to `:latest`, and untag the previous image with that tag. For more information on Docker tags, see the Docker https://docs.docker.com/engine/reference/commandline/tag/[documentation]. 

You can see your pushed images by viewing the repository in the ECS Console. Alternatively, you can use the CLI:

```
$ aws ecr list-images --repository-name=ecs-lab-api
{
    "imageIds": [        {
            "imageTag": "latest", 
            "imageDigest": "sha256:f0819d27f73c7fa6329644efe8110644e23c248f2f3a9445cbbb6c84a01e108f"
        }  
    ]
}
```

You have successfully completed Lab 1! Keep all the infrastructure you have built running. You will be building on this in Lab 2.
